# Curso de Expressões regulares do Otávio Miranda.

import re

empresas = """
DENOM_SOCIAL
2W ENERGIA S.A.
3R PETROLEUM OLÉO E GÁS S.A.
521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJUDICIAL
524 PARTICIPAÇOES SA
ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.
AEGEA SANEAMENTO E PARTICIPAÇÕES S.A.
AERIS IND. E COM. DE EQUIP. PARA GER. DE ENG. S.A.
AES TIETÊ ENERGIA S.A
AFLUENTE TRANSMISSÃO DE ENERGIA ELETRICA S/A
AGUAS GUARIROBA S.A.
ALEF SA
ALFA HOLDINGS SA
ALGAR TELECOM S/A
ALGAR TELECOM S/A
ALIANSCE SONAE SHOPPING CENTERS S.A.
ALLIED TECNOLOGIA S.A.
ALLPARK EMPREENDIMENTOS, PARTICIPAÇÕES E SERVIÇOS S.A.
ALPARGATAS SA
ALPER CONSULTORIA E CORRETORA DE SEGUROS S.A.
ALPHAVILLE S.A.
ALTERE SECURITIZADORA S.A.
ALUPAR INVESTIMENTO S/A
AMBEV S.A.
AMBIPAR PARTICIPAÇÕES E EMPREENDIMENTOS S.A.
AMPLA ENERGIA E SERVIÇOS S.A.
ANIMA HOLDING S/A
ÁQUILLA SECURITIZADORA SA
AREZZO INDÚSTRIA E COMERCIO S/A
ARGO ENERGIA EMPREENDIMENTOS E PARTICIPAÇÕES S.A.
ARGO TRANSMISSÃO DE ENERGIA S.A.
ARTERIS S.A.
ATACADÃO S.A.
ATMA  PARTICIPAÇÕES  S.A.
ATOM EMPREENDIMENTOS E PARTICIPAÇÕES S.A.
AUTOPISTA FERNÃO DIAS SA
AUTOPISTA FLUMINENSE SA
AUTOPISTA LITORAL SUL
AUTOPISTA PLANALTO SUL SA
AUTOPISTA REGIS BITTENCOURT SA
AZEVEDO & TRAVASSOS SA
AZUL S.A.
B2W - COMPANHIA DIGITAL
B3 S.A. - BRASIL, BOLSA, BALCÃO
BAHEMA EDUCACAO S.A.
BANCO ABC BRASIL S/A
BANCO ALFA DE INVESTIMENTO S.A.
BANCO BMG S/A
BANCO BRADESCO S.A.
BANCO BTG PACTUAL S/A
BANCO DA AMAZÔNIA S.A.
BANCO DAYCOVAL S.A.
BANCO DO BRASIL S.A.
BANCO DO ESTADO DE SERGIPE SA
BANCO DO ESTADO DO PARÁ S/A.
BANCO DO ESTADO DO RIO GRANDE DO SUL SA
BANCO DO NORDESTE DO BRASIL SA
BANCO ECONOMICO SA - EM LIQUIDAÇÃO EXTRAJUDICIAL
BANCO INDUSVAL S.A.
BANCO INTER S.A.
BANCO MERCANTIL BRASIL SA
BANCO MERCANTIL DE INVESTIMENTOS S.A.
BANCO NACIONAL S.A. - EM LIQUIDAÇÃO EXTRAJUDICIAL
BANCO PAN SA
BANCO PINE S/A
BANCO RCI BRASIL S.A.
BANCO SANTANDER (BRASIL) S.A.
BANESTES SA BANCO DO ESTADO DO ESPIRITO SANTO
BANRISUL ARMAZENS GERAIS SA
BANRISUL CARTÕES S.A.
BARDELLA S.A. INDS MECANICAS - EM RECUPERAÇÃO JUDICIAL
BARIGUI SECURITIZADORA SA
BASE SECURITIZADORA DE CRÉDITOS IMOBILIÁRIOS S.A.
BATTISTELLA ADM E PARTICIPAÇÕES S A
BAUMER SA
BB SEGURIDADE PARTICIPAÇÕES S.A.
BBM LOGÍSTICA S.A.
BCBF PARTICIPAÇÕES S.A.
BETAPART PARTICIPAÇÕES SA
BICICLETAS MONARK SA
BIOMM SA
BIOSEV S.A.
BK BRASIL OPERAÇÃO E ASSESSORIA A RESTAURANTES S.A.
BLAU FARMACÊUTICA S.A.
BNDES PARTICIPAÇÕES S.A. - BNDESPAR
BOA VISTA SERVIÇOS S.A.
BOMBRIL SA
BONAIRE PARTICIPAÇÕES S.A.- EM LIQUIDAÇÃO
BR MALLS PARTICIPAÇOES S.A.
BR PROPERTIES S.A.
BRADESCO LEASING S.A. - ARRENDAMENTO MERCANTIL
BRADESPAR S/A
BRASIL BROKERS PARTICIPAÇÕES SA
BRASIL SECURITIZADORA S.A.
BRASILAGRO CIA BRAS DE PROP AGRICOLAS
BRASILIANA PARTICIPAÇÕES S.A.
BRASKEM S.A.
BRAZIL REALTY CIA SECURITIZADORA DE CREDITOS IMOLIARIOS
BRAZILIAN FINANCE & REAL ESTATE S.A.
BRAZILIAN SECURITIES CIA SECURITIZAÇÃO
BRB-BANCO DE BRASILIA SA
BRF S.A.
BRK AMBIENTAL PARTICIPAÇÕES S.A.
BRPR 56 SECURITZADORA CRED IMOB SA
BRQ SOLUÇÕES EM INFORMÁTICA S.A.
BSI CAPITAL SECURITIZADORA S.A.
BTGI QUARTZO PARTICIPAÇÕES S.A.
BTGI SAFIRA PARTICIPAÇÕES S.A.
C&A MODAS S.A.
CABINDA PARTICIPAÇÕES SA
CACHOEIRA PAULISTA TRANSMISSORA DE ENERGIA SA
CACONDE PARTICIPAÇÕES SA
CAIANDA PARTICIPAÇÕES SA
CAIXA ADM DIV PUB ESTADUAL SA
CAIXA SEGURIDADE PARTICIPAÇÕES S.A.
CAMBUCI SA
CAMIL ALIMENTOS S/A
CAPITALE SECURITIZADORA DE CREDITO S.A.
CARBOMIL SA MINER. E INDUSTRIA
CASA DE PEDRA SECURITIZADORA DE CRÉDITO S.A.
CCB BRASIL ARRENDAMENTO MERCANTIL S/A
CCR S.A.
CCX CARVÃO DA COLOMBIA S.A. - EM LIQUIDAÇÃO
CEL PARTICIPAÇÕES S.A. - CELPAR
CELEO REDES TRANSMISSÃO DE ENERGIA S.A.
CEMEPE INVESTIMENTOS SA
CEMIG DISTRIBUIÇÃO S/A
CEMIG GERAÇÃO E TRANSMISSÃO S/A
CENTRAIS ELETRICAS BRASILEIRAS SA
CENTRAIS ELETRICAS DE SANTA CATARINA S.A
CENTRO DE IMAGEM DIAGNÓSTICOS S.A.
CESP - COMPANHIA ENERGÉTICA DE SÃO PAULO
CIA CAT. DE ÁGUAS E SANEAMENTO - CASAN
CIA DE ELETRICIDADE DO ESTADO DA BAHIA - COELBA
CIA DE PARTICIPAÇÕES ALIANÇA DA BAHIA
CIA ENERG CEARA - COELCE
CIA ENERG MINAS GERAIS - CEMIG
CIA ENERGÉTICA DE PERNAMBUCO - CELPE
CIA ENERGÉTICA DO RIO GRANDE DO NORTE
CIA ESTADUAL DE ÁGUAS E ESGOTOS - CEDAE
CIA ESTADUAL DE DISTRIBUIÇÃO DE ENERGIA ELETRICA
CIA ESTADUAL DE GERACAO E TRANSMISSAO DE ENERGIA ELETRICA
CIA FERRO LIGAS BAHIA FERBASA
CIA HERING
CIA HIDRO ELÉTRICA DO SÃO FRANCISCO
CIA INDUSTRIAL SCHLOSSER S.A.
CIA PIRATININGA DE FORÇA E LUZ
CIA PROVINCIA DE SECURITIZAÇÃO
CIA RIOGRANDENSE DE SANEAMENTO
CIA SANEAMENTO BÁSICO ESTADO SÃO PAULO
CIA SEGUROS ALIANCA BAHIA
CIA SIDERURGICA NACIONAL
CIA TECIDOS NORTE DE MINAS - COTEMINAS
CIA TECIDOS SANTANENSE
CIA. DE SANEAMENTO DO PARANÁ - SANEPAR
CIA. DISTRIB. DE GÁS DO RIO DE JANEIRO
CIA. SECURITIZADORA DE CRÉDITOS FINANCEIROS VERT-RECARGAPAY
CIBRASEC CIA BRASILEIRA DE SECURITIZAÇÃO
CIELO S.A.
CIMS SA
CINESYSTEM S.A.
CLARO TELECOM PARTICIPAÇÕES S.A.
COBRASMA SA
COBUCCIO SECURITIZADORA DE CRÉDITOS S.A.
COGNA EDUCAÇÃO S.A.
COMPANHIA  MELHORAMENTOS DE SÃO PAULO
COMPANHIA BRASILEIRA DE DISTRIBUIÇÃO
COMPANHIA CELG DE PARTICIPAÇÕES
COMPANHIA DE ÁGUA E ESGOTO DO CEARÁ
COMPANHIA DE FIACAO E TECIDOS CEDRO E CACHOEIRA
COMPANHIA DE GÁS DE MINAS GERAIS - GASMIG
COMPANHIA DE GÁS DE SÃO PAULO - COMGÁS
COMPANHIA DE LOCAÇÃO DAS AMERICAS
COMPANHIA DE SANEAMENTO DE MINAS GERAIS
COMPANHIA DE SANEAMENTO DO TOCANTINS - SANEATINS
COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB
COMPANHIA ENERGÉTICA JAGUARA
COMPANHIA ENERGÉTICA MIRANDA
COMPANHIA ENERGÉTICA SINOP S.A.
COMPANHIA INDUSTRIAL CATAGUASES
COMPANHIA ITAUNENSE ENERGIA E PARTICIPAÇÕES
COMPANHIA MINEIRA DE AÇUCAR E ALCOOL PARTICIPAÇÕES
COMPANHIA PARANAENSE DE ENERGIA
COMPANHIA PAULISTA DE FORCA LUZ - CPFL
COMPANHIA PAULISTA DE SECURITIZAÇÃO
COMPANHIA SEC. DE CRÉDITOS FIN. CARTÕES CONSIGNADOS BMG
COMPANHIA SECURITIZADORA DE CRÉD. FINANCEIROS VERT-FINTECH
COMPANHIA SECURITIZADORA DE CRÉD. FINANCEIROS VERT-NEXOOS
COMPANHIA SECURITIZADORA DE CREDITOS FINANCEIROS VERT-GYRA
COMPANHIA SECURITIZADORA DE CRÉDITOS FINANCEIROS VERT-PROVI
COMPANHIIA HABITASUL DE PARTICIPAÇÕES
COMPASS GÁS E ENERGIA S.A.
CONC RODOVIAS DO TIETÊ S.A.- EM RECUPERAÇÃO JUDICIAL
CONC. DO AEROPORTO INTERNACIONAL DE GUARULHOS S.A.
CONCEBRA - CONCESSIONARIA DAS RODOVIAS CENTRAIS DO BRASIL S.A.
CONCESSÃO METROVIÁRIA DO RIO DE JANEIRO SA
CONCESSIONARIA AUTO RAPOSO TAVARES SA-CART
CONCESSIONÁRIA BR-040 S.A.
CONCESSIONÁRIA DA RODOVIA MG-050 S.A.
CONCESSIONÁRIA DAS RODOVIAS AYRTON SENNA E CARVALHO PINTO S/A-ECOPISTAS
CONCESSIONÁRIA DAS RODOVIAS INTEGRADAS DO SUL S.A.
CONCESSIONÁRIA DE RODOVIA SUL-MATOGROSSENSE S.A.
CONCESSIONARIA DE RODOVIAS DO INTERIOR PAULISTA S/A
CONCESSIONARIA DE RODOVIAS DO OESTE DE SP-VIA OESTE SA
CONCESSIONÁRIA DO SISTEMA ANHANGUERA-BANDEIRANTES S.A.
CONCESSIONARIA ECOVIAS DOS IMIGRANTES SA
CONCESSIONARIA PONTE RIO-NITERÓI S.A. - ECOPONTE
CONCESSIONARIA RIO-TERESOPOLIS SA
CONCESSIONÁRIA ROTA DAS BANDEIRAS S/A
CONCESSIONÁRIA ROTA DO OESTE S.A.
CONPEL CIA. NORDESTINA DE PAPEL - EM RECUPERAÇÃO JUDICIAL
CONSERVAS ODERICH SA
CONSIG 6 | COMPANHIA SECURITIZADORA DE CRÉDITOS FINANCEIROS
CONSIGNADOS I COMPANHIA SECURITIZADORA DE CRÉDITOS FINANCEIROS
CONSORCIO ALFA DE ADMINISTRAÇÃO SA
CONST ADOLPHO LINDENBERG SA
CONST SULTEPA SA - EM RECUPERAÇÃO JUDICIAL
CONSTRUTORA TENDA S/A
COPEL GERAÇÃO E TRANSMISSÃO S/A
CORREA RIBEIRO SA COM IND
COSAN LOGÍSTICA S.A.
COSAN S.A.
CPFL ENERGIA SA
CPFL ENERGIAS RENOVÁVEIS S.A.
CPFL GERAÇÃO DE ENERGIA S/A
CR2 EMPREENDIMENTOS IMOBILIÁRIOS S/A
CSA-COMPANHIA SECURITIZADORA DE ATIVOS
CSU CARDSYSTEM S/A
CTC - CENTRO DE TECNOLOGIA CANAVIEIRA S.A.
CTEEP-CIA TRANSM ENERGIA ELÉTR. PAULISTA
CURY CONSTRUTORA E INCORPORADORA S.A.
CVC BRASIL OPERADORA E AGÊNCIA DE VIAGENS SA
CYRELA BRAZIL REALTY SA EMPRS E PARTS
CYRELA COMMERCIAL PROPERTIES SA EMP  PART
D1000 VAREJO FARMA PARTICIPAÇÕES S.A.
DIAGNOSTICOS DA AMERICA SA
DIBENS LEASING S.A.- ARREND. MERCANTIL
DIMED SA DISTRIBUIDORA DE MEDICAMENTOS
DINAMICA ENERGIA S/A
DIRECIONAL ENGENHARIA SA
DOHLER S.A.
DOMMO ENERGIA S.A.
DTCOM - DIRECT TO COMPANY S.A.
DURATEX S.A.
ECO. SEC. DTOS. CREDIT. AGRONEGÓCIOS S/A
ECO050 - CONCESSIONÁRIA DE RODOVIAS S.A.
ECO101 CONCESSIONÁRIA DE RODOVIAS S.A.
ECORODOVIAS CONCESSÕES E SERVIÇOS S/A
ECORODOVIAS INFRAESTRUTURA E LOGÍSTICA S.A.
EDP ENERGIAS DO BRASIL S/A
EDP ESPIRITO SANTO DISTRIBUIÇÃO DE ENERGIA S.A.
EDP SÃO PAULO DISTRIBUIÇÃO DE ENERGIA S.A.
ELDORADO BRASIL CELULOSE S.A.
ELECTRO AÇO ALTONA S/A
ELEKTRO REDES S.A.
ELETROBRÁS PARTICIPAÇÕES S.A. - ELETROPAR
ELETROPAULO METROPOLITANA EL.S.PAULO S.A
ELFA MEDICAMENTOS S.A.
EMAE-EMP.METROPOLITANA ÁGUAS ENERGIA S.A
EMBRAER S.A.
EMP.NAC. DE COMÉRCIO, RÉDITO E PART. S.A. - ENCORPAR
EMPREENDIMENTOS PAGUE MENOS SA
ENAUTA PARTICIPAÇÕES S.A.
ENCALSO PARTICIPAÇÕES EM CONCESSÕES S.A.
ENERGISA MATO GROSSO - DISTRIBUIDORA DE ENERGIA S.A.
ENERGISA MATO GROSSO DO SUL - DISTRIBUIDORA DE ENERGIA S/A
ENERGISA MINAS GERAIS - DISTRIBUIDORA DE ENERGIA S/A
ENERGISA PARAÍBA - DISTRIBUIDORA DE ENERGIA S/A
ENERGISA SA
ENERGISA SERGIPE - DISTRIBUIDORA DE ENERGIA S/A
ENERGISA SUL-SUDESTE - DISTRIBUIDORA DE ENERGIA S.A.
ENERGISA TRANSMISSÃO DE ENERGIA S.A.
ENEVA S.A.
ENGIE BRASIL ENERGIA S.A.
ENJOEI.COM.BR ATIVIDADES DE INTERNET S.A.
ENTREVIAS CONCESSIONÁRIA DE RODOVIAS S.A.
EQUATORIAL ENERGIA S/A
EQUATORIAL MARANHÃO DISTRIBUIDORA DE ENERGIA S.A.
EQUATORIAL PARÁ DISTRIBUIDORA DE ENERGIA S.A.
EQUATORIAL TRANSMISSORA 7 SPE S.A.
EQUATORIAL TRANSMISSORA 8 SPE S.A.
ETERNIT S.A.- EM RECUPERAÇÃO JUDICIAL
EUCATEX SA IND E COMERCIO
EVEN CONSTRUTORA E INCORPORADORA S/A
EXCELSIOR ALIMENTOS SA.
EZ INC INCORPORAÇÕES COMERCIAIS S.A.
EZ TEC EMPREEND. E PARTICIPAÇÕES S/A
FARMÁCIA E DROGARIA NISSEI S.A.
FELCAR SECURITIZADORA S.A.
FENICIAPAR S/A
FERREIRA GOMES ENERGIA S.A.
FERROVIA CENTRO ATLANTICA SA
FERROVIA NORTE SUL S/A
FERTILIZANTES HERINGER S.A. - EM RECUPERAÇÃO JUDICIAL
FIACAO E TECELAGEM SAO JOSE S/A - EM RECUPERAÇÃO JUDICIAL
FILADÉLFIA SECURITIZADORA S/A.
FINANCEIRA ALFA S.A.- C.F.I
FINANSINOS S/A-CRÉDITO, FINAN. E INVEST.
FLEURY SA
FLEX GESTÃO DE RELACIONAMENTO S.A.
FONTAINE VILLE PARTICIPAÇÕES S/A
FORPART S.A. - EM LIQUIDAÇÃO
FORTE SECURITIZADORA S.A.
FORTUNATO SECURITIZADORA S.A.
FRAS-LE SA
FTL - FERROVIA TRANSNORDESTINA LOGÍSTICA S.A.
FUTURETEL S.A. - EM LIQUIDAÇÃO
GAFISA SA
GAIA AGRO SECURITIZADORA S.A.
GAIA CRED SECURITIZADORA DE CRÉDITOS FINANCEIROS S.A.
GAIA SECURITIZADORA S/A
GAMA PARTICIPAÇÕES S.A.
GENERAL SHOPPING E OUTLETS DO BRASIL S.A.
GERDAU S.A.
GOL LINHAS AEREAS INTELIGENTES SA
GPC PARTICIPACOES SA
GRANBIO INVESTIMENTOS S.A.
GRAZZIOTIN SA
GRENDENE SA
GRUPO DE MODA SOMA S.A.
GRUPO MATEUS S.A.
GRUPO SBF S.A.
GUARARAPES CONFECÇÕES SA
GUARDIAN COMPANHIA SECURITIZADORA
HABITASEC SECURITIZADORA SA
HAGA S.A. INDÚSTRIA E COMÉRCIO
HAPVIDA PARTICIPAÇÕES E INVESTIMENTOS S.A.
HAUSCENTER SA
HBR REALTY EMPREENDIMENTOS IMOBILIÁRIOS S.A.
HELBOR EMPREENDIMENTOS S/A
HERCULES S/A - FABRICA DE TALHERES
HIDROVIAS DO BRASIL S.A.
HLASA PARTICIPAÇÕES S.A.
HOTEIS OTHON SA
HOUSI S.A.
HYPERA S/A
IGB ELETRÔNICA S.A. - EM RECUPERAÇÃO JUDICIAL
IGUA SANEAMENTO S.A.
IGUATEMI EMPRESA DE SHOPPING CENTERS S/A
INBRANDS SA
INDS J B DUARTE SA
INDÚSTRIAS ROMI S.A.
INEPAR EQUIPAMENTOS E MONTAGENS S.A. - EM RECUPERAÇÃO JUDICIAL
INEPAR SA IND E CONSTRUÇÕES - EM RECUPERAÇÃO JUDICIAL
INFRASEC SECURITIZADORA S/A
INSTITUTO HERMES PARDINI S/A
INTER CONSTRUTORA E INCORPORADORA S.A
INTERNATIONAL MEAL COMPANY ALIMENTAÇÃO S.A.
INVEST.E PART.EM INFRA-ESTR.S/A-INVEPAR
INVESTCO S/A
INVESTIMENTOS BEMGE S.A.
IOCHPE-MAXION SA
IRANI PAPEL E EMBALAGEM S.A.
IRB - BRASIL RESSEGUROS S.A.
ISEC SECURITIZADORA S.A.
ITAPEBI GERAÇÃO DE ENERGIA S/A
ITAÚ UNIBANCO HOLDING S.A.
ITAUSA S.A.
J.MACEDO S/A
JBS SA
JEREISSATI PARTICIPAÇÕES S/A
JHSF MALLS S.A.
JHSF PARTICIPAÇÕES SA
JOSAPAR- JOAQUIM OLIVEIRA S/A PARTICIP
JSL S.A.
K-INFRA RODOVIA DO AÇO S.A.
KARSTEN SA
KEPLER WEBER SA
KLABIN S.A.
KOSMOS COMÉRCIO DE VESTUÁRIO S/A - EM RECUPERAÇÃO JUDICIAL
LAVVI EMPREENDIMENTOS IMOBILIÁRIOS S.A
LEADS CIA. SECURITIZADORA
LIFEMED INDUSTRIAL DE EQUIP. E ART. MEDICOS E HOSP. S.A.
LIGHT ENERGIA S.A.
LIGHT SA
LIGHT SERVIÇOS DE ELETRICIDADE SA
LINHA AMARELA S.A.- LAMSA
LINHAS DE MACAPÁ TRANSMISSORA DE ENERGIA S.A.
LINHAS DE XINGU TRANSMISSORA DE ENERGIA S.A.
LINX S.A.
LITEL PARTICIPACOES SA
LITELA PARTICIPAÇÕES S.A.
LM TRANSPORTES INTERESTADUAIS SERVIÇOS E COMÉRCIO S.A.
LOCALIZA  FLEET S.A.
LOCALIZA RENT A CAR SA
LOCAWEB SERVIÇOS DE INTERNET S.A.
LOG COMMERCIAL PROPERTIES E PARTICIPAÇÕES S.A.
LOG-IN LOGISTICA INTERMODAL SA
LOGOS COMPANHIA SECURITIZADORA S/A
LOJAS AMERICANAS SA
LOJAS QUERO-QUERO S.A.
LOJAS RENNER SA
LPS BRASIL CONSULTORIA DE IMOVEIS S/A
LUPATECH S/A - EM RECUPERAÇÃO JUDICIAL
M DIAS BRANCO SA IND E COM DE ALIMENTOS
MAESTRO LOCADORA DE VEÍCULOS S.A.
MAGAZINE LUIZA SA
MAHLE METAL LEVE S.A.
MANGELS INDUSTRIAL S.A.
MANUFATURA DE  BRINQUEDOS ESTRELA SA
MARCOPOLO SA
MARFRIG GLOBAL FOODS SA
MARINA DE IRACEMA PARK SA
MARISA LOJAS SA
MASSA FALIDA DA BRASIL PHARMA SA
MASSA FALIDA DA SA IND E COMERCIO CHAPECO
MBK SECURITIZADORA S/A
MELIUZ S.A.
MELNICK DESENVOLVIMENTO IMOBILIÁRIO S.A.
MENDES JUNIOR ENGENHARIA SA
MERCANTIL DO BR FINC SA CFI
METALFRIO SOLUTIONS S/A
METALGRAFICA IGUACU SA
METALURGICA GERDAU SA
METALURGICA RIOSULENSE SA
METANOR SA METANOL DO NE
METISA METALÚRGICA  TIMBOENSE SA
MGI - MINAS GERAIS PARTICIPAÇÕES S.A.
MILLS ESTRUTURAS E SERVIÇOS DE ENGENHARIA S/A
MINASMAQUINAS SA
MINERVA S/A
MINUPAR PARTICIPACOES SA
MISSISSIPI SECURITIZADORA S/A
MITRE REALTY EMPREENDIMENTOS E PARTICIPAÇÕES S.A.
MLOG S.A.
MMX MINERAÇÃO E METÁLICOS S.A. - EM RECUPERAÇÃO JUDICIAL
MONTEIRO ARANHA SA
MOURA DUBEUX ENGENHARIA S/A
MOVIDA PARTICIPAÇÕES S.A.
MRS LOGÍSTICA S/A
MRV ENGENHARIA E PARTICIPAÇÕES S/A
MULTINER S/A
MULTIPLAN EMP. IMOBILIARIOS S/A
MUNDIAL S.A - PRODUTOS DE CONSUMO
NASA SECURITIZADORA S.A.
NATURA & CO HOLDING S.A.
NATURA COSMETICOS SA
NCF PARTICIPAÇÕES S.A.
NEOENERGIA S.A
NEOGRID PARTICIPACÕES S.A.
NEUMARKT TRADE AND FINANCIAL CENTER S/A
NEWTEL PARTICIPAÇÕES S.A. - EM LIQUIDAÇÃO
NORDON INDS METALURGICAS SA
NORTE BRASIL TRANSMISSORA DE ENERGIA S.A.
NORTE ENERGIA S.A
NORTEC QUIMICA S.A.
NOTRE DAME INTERMÉDICA PARTICIPAÇÕES S.A.
NOVA TRANSPORTADORA DO SUDESTE S.A. - NTS
NUTRIPLANT INDUSTRIA E COMÉRCIO S/A
OCEANA OFFSHORE S.A.
OCTANTE SECURITIZADORA SA
ODONTOPREV S/A
OI S.A. - EM RECUPERAÇÃO JUDICIAL
OMEGA GERAÇÃO S.A.
OPPORTUNITY ENERGIA E PARTICIPAÇÕES S.A.
OSX BRASIL S.A.
OURINVEST SECURITIZADORA S.A.
OURO FINO SAÚDE ANIMAL PARTICIPAÇÕES S.A.
OURO VERDE LOCAÇÃO E SERVIÇO S.A.
PACAEMBU CONSTRUTORA S.A.
PADTEC HOLDING S.A.
PAN ARRENDAMENTO MERCANTIL S.A.
PANATLANTICA SA
PARANA BANCO S.A.
PARANAPANEMA SA
PARCOM PARTICIPACOES SA
PARTICIPAÇÕES INDUST. DO NORDESTE S.A.
PÁTRIA COMPANHIA SECURITIZADORA DE CRÉDITOS IMOBILIÁRIOS
PATRIMAR ENGENHARIA S.A.
PBG S/A
PDG COMPANHIA SECURITIZADORA - EM RECUPERAÇÃO JUDICIAL
PDG REALTY SA EMPREENDIMENTOS E PARTS - EM RECUPERAÇÃO JUDICIAL
PET CENTER COMÉRCIO E PARTICIPAÇÕES S.A.
PETRO RIO S.A.
PETROBRAS DISTRIBUIDORA SA
PETRÓLEO BRASILEIRO  S.A.  - PETROBRAS
PETROLEO LUB DO NORDESTE SA
PETTENATI SA IND TEXTIL
PJBANK SECURITIZADORA S.A.
PLANO & PLANO DESENVOLVIMENTO IMOBILIÁRIO S.A.
PLASCAR PARTICIPAÇÕES INDUSTRIAIS S.A
POLO CAPITAL SECURITIZADORA S/A
POLPAR S.A.
POMIFRUTAS S/A - EM RECUPERAÇÃO JUDICIAL
PORTO SEGURO SA
PORTO SUDESTE V.M. S.A.
PORTUENSE FERRAGENS S/A
POSITIVO TECNOLOGIA S.A.
PRÁTICA KLIMAQUIP INDÚSTRIA E COMÉRCIO S.A.
PRINER SERVIÇOS INDUSTRIAIS S.A.
PRODUTORES ENERGETICOS DE MANSO SA
PROFARMA DISTRIB. PRODUTOS FARMACEUTICOS
PROLAGOS S.A. - CONCESSIONÁRIA DE SERVIÇOS PÚBLICOS DE ÁGUA E ESGOTO
PROMPT PARTICIPAÇÕES S.A.
QUALICORP SA
QUALITY SOFTWARE S.A.
RAIA DROGASIL S.A.
RAÍZEN ENERGIA S.A.
RANDON S.A. IMPLEMENTOS E PARTICIPAÇÕES
RB CAPITAL COMPANHIA DE SECURITIZAÇÃO
REAG SECURITIES - SECURITIZADORA DE CRÉDITOS S/A
REAL AI PIC SECURITIZADORA DE CREDITOS IMOBILIARIOS S.A.
RECRUSUL SA
REDE D'OR SÃO LUIZ S.A.
REDE ENERGIA PARTICIPAÇÕES S.A.
REFINARIA PET MANGUINHOS SA
REIT SECURITIZADORA DE RECEBIVEIS IMOBILIÁRIOS S/A
RENOVA COMP. SECURITIZ. DE CRÉDITOS FINANC. S.A.
RENOVA ENERGIA S.A. -  EM RECUPERAÇÃO JUDICIAL
RESTOQUE COMÉRCIO E CONFECÇÕES DE ROUPAS SA
RGE SUL DISTRIBUIDORA DE ENERGIA S.A.
RIO PARANAPANEMA ENERGIA SA
RIOLOAN 2 COMPANHIA SECURITIZADORA DE CRÉDITOS FINANCEIROS
RIVA 9 EMPREENDIMENTOS IMOBILIARIOS S/A
RNI NEGÓCIOS IMOBILIÁRIOS S.A.
RODONORTE - CONC. ROD. INTEGRADAS S.A.
RODOVIAS DAS COLINAS S.A.
ROMAXIS SECURITIZADORA S.A.
ROSSI RESIDENCIAL SA
RUGE SECURITIZADORA DE CRÉDITOS FINANCEIROS S.A.
RUMO MALHA NORTE S.A.
RUMO MALHA OESTE S.A.
RUMO MALHA PAULISTA S.A.
RUMO MALHA SUL S.A.
RUMO S.A.
SABER SERVIÇOS EDUCACIONAIS S.A.
SALUS INFRAESTRUTURA PORTUÁRIA S.A.
SANEAMENTO DE GOIAS SA
SANESALTO SANEAMENTO SA
SANSUY SA INDÚSTRIA  DE PLASTICOS
SANTA CATARINA PART INVEST SA
SANTHER FAB.DE PAPEL SANTA THEREZINHA SA
SANTO ANTONIO ENERGIA S.A.
SANTOS BRASIL PARTICIPAÇÕES S.A.
SÃO CARLOS EMPREENDS E PARTICIPAÇÕES S.A
SÃO MARTINHO SA
SÃO PAULO TURISMO S. A.
SARAIVA LIVREIROS S.A. - EM RECUPERAÇÃO JUDICIAL
SBF COMÉRCIO DE PRODUTOS ESPORTIVOS S.A.
SCHULZ SA
SEIVA S.A. - FLORESTAS E INDÚSTRIAS
SENDAS DISTRIBUIDORA S.A.
SENECA COMPANHIA SECURITIZADORA
SEQUOIA LOGÍSTICA E TRANSPORTES S.A.
SER EDUCACIONAL S.A.
SERRA AZUL WATER PARK SA
SIDERURGICA J L ALIPERTI SA
SIMPAR S.A.
SINQIA S.A.
SLC AGRICOLA SA
SMARTFIT ESCOLA DE GINÁSTICA E DANÇA S.A.
SMILES FIDELIDADE S.A.
SNB PARTICIPACOES SA
SOC.DE ABASTEC.DE ÁGUA E SANEAMENTO S.A.
SONDOTECNICA ENGENHARIA DE SOLOS S/A.
SPRINGER SA
SPRINGS GLOBAL PARTICIPAÇÕES S/A
STARA S.A. - INDÚSTRIA DE IMPLEMENTOS AGRÍCOLAS
STATKRAFT ENERGIAS RENOVÁVEIS S.A.
SUDESTE SA
SUGOI S.A.
SUL 116 PARTICIPAÇÕES S.A.
SUL AMERICA S/A
SUZANO HOLDING S.A.
SUZANO S.A.
T4F ENTRETENIMENTO SA
TAURUS ARMAS S.A.
TCP - TERMINAL DE CONTÊINERES DE PARANAGUÁ S.A.
TECBLU - TECELAGEM BLUMENAU S/A.
TECHNOS SA
TECNISA S/A
TECNOSOLO S/A - EM RECUPERAÇÃO JUDICIAL
TEGMA GESTÃO LOGÍSTICA SA
TEKA TECELAGEM KUEHNRICH SA - EM RECUPERAÇÃO JUDICIAL
TEKNO S.A. INDÚSTRIA E COMÉRCIO
TELEC. BRASILEIRAS S.A. - TELEBRÁS
TELEFÔNICA BRASIL S.A.
TERMELÉTRICA PERNAMBUCO III S.A.
TERMINAIS PORT. DA PONTA DO FÉLIX S/A
TERMINAL GARAGEM MENEZES CORTES SA
TERMOPERNAMBUCO SA
TERRA SANTA AGRO S.A.
TÊXTIL RENAUXVIEW S/A
TIM S.A.
TOTVS S.A
TPI - TRIUNFO PARTICIPACOES E INVESTIMENTOS S.A.
TRACK & FIELD CO S.A
TRANSBRASILIANA CONCESSIONÁRIA DE RODOVIA SA
TRANSMISSORA ALIANÇA DE ENERGIA ELÉTRICA S.A.
TRANSNORDESTINA LOGISTICA SA
TRAVESSIA SECURITIZADORA DE CRÉDITOS FINANCEIROS XIV S.A
TRAVESSIA SECURITIZADORA S.A.
TREVISA  INVESTIMENTOS SA
TRIÂNGULO DO SOL AUTO-ESTRADAS S.A.
TRIPLE PLAY BRASIL PARTICIPAÇÕES S.A.
TRISUL S/A
TRONOX PIGMENTOS DO BRASIL S.A.
TRUE SECURITIZADORA S.A.
TRX SECURITIZADORA S.A.
TUPY SA
ULTRAPAR PARTICIPAÇÕES SA
UNICASA INDÚSTRIA DE MÓVEIS S.A.
UNIDAS S/A
UNIPAR CARBOCLORO S.A.
UP ENGENHARIA E URBANISMO S.A.
UPTICK PARTICIPACOES SA
USINA TERMELÉTRICA PAMPA SUL S.A.
USINAS SIDERURGICAS DE MINAS GERAIS SA
VALE S.A.
VALID SOLUÇÕES S.A.
VAMOS LOCAÇÃO DE CAMINHÕES, MÁQUINAS E EQUIPAMENTOS S.A.
VENTOS DO SUL ENERGIA S.A.
VENTURE CAPITAL PARTICIPAÇÕES E INVESTIMENTOS S.A.
VERT COMPANHIA SECURITIZADORA
VIA VAREJO S.A.
VIABAHIA CONCESSIONÁRIA DE RODOVIAS SA
VIARONDON CONCESSIONÁRIA DE RODOVIA SA
VISION SECURITIZADORA
VIVARA PARTICIPAÇÕES S.A.
VIVER INCORP. E CONSTRUTORA S.A.- EM RECUPERAÇÃO JUDICIAL
VIX LOGÍSTICA S/A
VULCABRAS|AZALEIA S.A.
WEG SA
WETZEL S.A. EM RECUPERAÇÃO JUDICIAL
WHIRLPOOL S.A
WIZ SOLUÇÕES E CORRETAGEM DE SEGUROS S.A.
WLM PART. E COMÉRCIO DE MÁQUINAS E VEÍCULOS S.A.
WTC AMAZONAS SUITE HOTEL S.A.
WTC RIO EMPREEND. E PARTICIPAÇÕES S.A.
XX DE NOVEMBRO INVESTIMENTOS E PARTICIPAÇÕES S.A
YDUQS PARTICIPACOES S.A.
YOU INC INCORPORADORA E PARTICIPAÇÕES S.A.

"""
ticker = 'WIZS3'
# regexp = re.compile(r'[[:alnun:]]', empresas)
print(re.findall(r'(ABVE)[ A-Z0-9]+', empresas))
